/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jyqqhw_jnidemo_JNI */

#ifndef _Included_com_jyqqhw_jnidemo_JNI
#define _Included_com_jyqqhw_jnidemo_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jyqqhw_jnidemo_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jyqqhw_jnidemo_JNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_jyqqhw_jnidemo_JNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jyqqhw_jnidemo_JNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jyqqhw_jnidemo_JNI
 * Method:    copy
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jyqqhw_jnidemo_JNI_copy
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
